### ISSUE TITLE
Finger Tree / https://github.com/mschauer/FingerTree.jl

### ISSUE THREAD

**Issue by mschauer** [JuliaLang/FunctionalCollections.jl#18]
(Via the mailing list, maybe I should mention it here:) A while ago I implemented a lot of functionality for finger trees, https://hackage.haskell.org/package/fingertree-0.0/docs/Data-FingerTree.html ,  a "functional representation of persistent sequences supporting access to the ends in amortized constant time, and concatenation and splitting in time logarithmic in the size of the smaller piece". If there is interest of merging this after some cleanup, please reopen.

**Comment by shashi** [comment]
It would surely be nice to have this included here, after a little clean up. Do you think the performance will be significantly better than that of PersistentVector in these specific cases?

**Comment by mschauer** [comment]
No unfortunately the performance is currently not in the same league, and some of that is certainly because of the inherent type unstability.
