### ISSUE TITLE
Can't append to PersistentVector with some types

### ISSUE THREAD

**Issue by jcrudy** [JuliaLang/FunctionalCollections.jl#21]
I get an error when trying to append to a PersistentVector{Symbol}, as well as some custom types.

    l = @Persistent [:a, :b]
    append(l, :c)
    ERROR: `start` has no method matching start(::Symbol)
      in mapfoldl at reduce.jl:71
      in append at /Users/jason/.julia/v0.3/FunctionalCollections/src/PersistentVector.jl:191

It seems to work fine with numbers, though.  For example:

    l = @Persistent [1, 2]
    append(l, 3)

behaves as expected.  I'm using Julia 0.3.10 on Mac OS 10.9.5.

**Comment by TotalVerb** [comment]
This is a documentation issue. `push` is the right function to add one argument; `append` by contrast adds elements of the given collection. The fact that numbers work is a consequence that, somewhat non-intuitively, numbers in Julia are collections of themselves.
